### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MrLeoDaVinci** [okiyama/PyAutoClicker#1]
when i run either of the auto clickers i get this error

Traceback (most recent call last):
  File "autoClickGUI.py", line 8, in <module>
    import pyxhook
  File "/home/quinn/PyAutoClicker/pyxhook.py", line 41, in <module>
    import Image
ImportError: No module named Image

**Comment by okiyama** [comment]
Give this Stackoverflow answer a look: https://stackoverflow.com/questions/12024397/no-module-named-image

It seems you need to install the PIL library.
